const CONTENT_TYPES = [
  'BLOG_POST',
  'SOCIAL_MEDIA',
  'EMAIL',
  'AD_COPY',
  'PRODUCT_DESCRIPTION',
  'PRESS_RELEASE',
  'NEWSLETTER',
  'VIDEO_SCRIPT',
  'OTHER',
];

const CONTENT_TONES = [
  'PROFESSIONAL',
  'CASUAL',
  'FRIENDLY',
  'PERSUASIVE',
  'INFORMATIVE',
  'HUMOROUS',
  'AUTHORITATIVE',
  'ENTHUSIASTIC',
];

const CONTENT_STATUSES = ['DRAFT', 'SCHEDULED', 'PUBLISHED', 'ARCHIVED'];

const CONTENT_LENGTHS = ['SHORT', 'MEDIUM', 'LONG'];

const NOTIFICATION_TYPES = [
  'CONTENT_GENERATED',
  'CONTENT_PUBLISHED',
  'CONTENT_SCHEDULED',
  'AI_SUGGESTION',
  'SYSTEM',
  'ACCOUNT',
];

const THEMES = ['LIGHT', 'DARK', 'SYSTEM'];

module.exports = {
  CONTENT_TYPES,
  CONTENT_TONES,
  CONTENT_STATUSES,
  CONTENT_LENGTHS,
  NOTIFICATION_TYPES,
  THEMES,
};
